# Generated by Django 4.2.21 on 2025-08-09 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_data', '0003_alter_studentdata_status'),
        ('user_profile', '0002_alter_userprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_links', to='student_data.studentdata')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='psychologist_links', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'Psychologist',
                'verbose_name_plural': 'Psychologists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile'], name='psychologis_user_pr_1d2c95_idx'), models.Index(fields=['student_data'], name='psychologis_student_d83c35_idx'), models.Index(fields=['created_at'], name='psychologis_created_c7840c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='psychologist',
            constraint=models.UniqueConstraint(fields=('user_profile', 'student_data'), name='uniq_psychologist_userprofile_student'),
        ),
    ]
