# Generated by Django 4.2.21 on 2025-06-02 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_number', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('foreign_language', models.CharField(max_length=50)),
                ('languages_score', models.FloatField()),
                ('human_sciences_score', models.FloatField()),
                ('natural_sciences_score', models.FloatField()),
                ('math_score', models.FloatField()),
                ('essay_score', models.FloatField()),
                ('pdf_file', models.FileField(upload_to='enem_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enem_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ENEM Result',
                'verbose_name_plural': 'ENEM Results',
                'indexes': [models.Index(fields=['cpf'], name='enem_enemre_cpf_825db2_idx')],
            },
        ),
    ]
