# Generated by Django 4.2.21 on 2025-06-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemresult',
            name='status',
            field=models.CharField(choices=[('fileSent', 'Arquivo Enviado'), ('processed', 'Processado'), ('invalid', 'Inválido'), ('approved', 'Aprovado')], default='fileSent', max_length=20),
        ),
    ]
