services:
  redis:
    container_name: backoffice-redis
    image: redis:7-alpine
    ports:
      - "6480:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: always

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
