# Generated by Django 4.2.21 on 2025-06-04 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seletivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMeritDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='academic_merit_documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Recusado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_merit_documents', to='seletivo.userdata')),
            ],
        ),
    ]
