# Generated by Django 4.2.21 on 2025-05-22 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seletivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cidade Permitida',
                'verbose_name_plural': 'Cidades Permitidas',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('birth_date', models.DateField()),
                ('social_name', models.CharField(blank=True, max_length=255, null=True)),
                ('celphone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('allowed_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seletivo.allowedcity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dados do Usuário',
                'verbose_name_plural': 'Dados dos Usuários',
            },
        ),
        migrations.AddIndex(
            model_name='allowedcity',
            index=models.Index(fields=['localidade', 'uf'], name='seletivo_al_localid_2b1ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='userdata',
            index=models.Index(fields=['cpf'], name='seletivo_us_cpf_cec1fb_idx'),
        ),
    ]
