# Generated by Django 4.2.21 on 2025-05-22 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seletivo', '0002_allowedcity_userdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_status', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('experience_duration', models.CharField(max_length=100)),
                ('programming_knowledge_level', models.CharField(max_length=100)),
                ('motivation_level', models.CharField(max_length=100)),
                ('project_priority', models.CharField(max_length=100)),
                ('weekly_available_hours', models.CharField(max_length=50)),
                ('study_commitment', models.CharField(max_length=100)),
                ('frustration_handling', models.CharField(max_length=255)),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='seletivo.userdata')),
            ],
        ),
    ]
