# Generated by Django 4.2.21 on 2025-05-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seletivo', '0003_persona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='experience',
            field=models.TextField(verbose_name='Experiência'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='experience_duration',
            field=models.CharField(max_length=100, verbose_name='Duração da Experiência'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='frustration_handling',
            field=models.CharField(max_length=255, verbose_name='Lidar com Frustração'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='motivation_level',
            field=models.CharField(max_length=100, verbose_name='Nível de Motivação'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='professional_status',
            field=models.CharField(max_length=255, verbose_name='Status Profissional'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='programming_knowledge_level',
            field=models.CharField(max_length=100, verbose_name='Nível de Programação'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='project_priority',
            field=models.CharField(max_length=100, verbose_name='Prioridade de Projeto'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='study_commitment',
            field=models.CharField(max_length=100, verbose_name='Comprometimento com Estudo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='weekly_available_hours',
            field=models.CharField(max_length=50, verbose_name='Horas Semanais Disponíveis'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['professional_status'], name='seletivo_pe_profess_cccf31_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['programming_knowledge_level'], name='seletivo_pe_program_6fa232_idx'),
        ),
    ]
