# Generated by Django 4.2.21 on 2025-05-22 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seletivo', '0004_alter_persona_options_alter_persona_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_address', models.TextField()),
            ],
            options={
                'verbose_name': 'Local de Exame',
                'verbose_name_plural': 'Locais de Exame',
                'indexes': [models.Index(fields=['name'], name='seletivo_ex_name_dd790c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='seletivo.examlocal')),
            ],
            options={
                'verbose_name': 'Data de Exame',
                'verbose_name_plural': 'Datas de Exame',
            },
        ),
        migrations.CreateModel(
            name='ExamHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('exam_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='seletivo.examdate')),
            ],
            options={
                'verbose_name': 'Horário de Exame',
                'verbose_name_plural': 'Horários de Exame',
                'indexes': [models.Index(fields=['hour'], name='seletivo_ex_hour_eeb1d3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='examdate',
            index=models.Index(fields=['date'], name='seletivo_ex_date_f68a9c_idx'),
        ),
    ]
