# Generated by Django 4.2.21 on 2025-05-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seletivo', '0005_examlocal_examdate_examhour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examlocal',
            name='allowed_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seletivo.allowedcity'),
        ),
    ]
