# Generated by Django 4.2.21 on 2025-05-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seletivo', '0006_examlocal_allowed_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=50)),
                ('exam_scheduled_hour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='seletivo.examhour')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='seletivo.userdata')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'indexes': [models.Index(fields=['status'], name='seletivo_ex_status_ea7e48_idx')],
            },
        ),
    ]
