# Generated by Django 4.2.21 on 2025-05-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seletivo', '0007_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('nationality', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='seletivo.userdata')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'indexes': [models.Index(fields=['cpf', 'name'], name='seletivo_gu_cpf_948990_idx')],
            },
        ),
    ]
