# Generated by Django 4.2.21 on 2025-05-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seletivo', '0008_guardian'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=255)),
                ('maritial_status', models.CharField(max_length=50)),
                ('family_income', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('pcd', models.CharField(max_length=255)),
                ('internet_type', models.CharField(max_length=100)),
                ('public_school', models.BooleanField(default=False)),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_data', to='seletivo.userdata')),
            ],
            options={
                'verbose_name': 'Dados de Registro',
                'verbose_name_plural': 'Dados de Registro',
                'indexes': [models.Index(fields=['profession', 'education_level'], name='seletivo_re_profess_831f5b_idx')],
            },
        ),
    ]
