# Generated by Django 4.2.21 on 2025-05-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seletivo', '0009_registrationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='seletivo.userdata')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'indexes': [models.Index(fields=['status'], name='seletivo_co_status_b5c8db_idx')],
            },
        ),
    ]
