# Generated by Django 4.2.21 on 2025-06-07 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seletivo', '0002_academicmeritdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(help_text='A unique 9-digit student registration number (e.g., 123456789).', max_length=100, unique=True)),
                ('corp_email', models.EmailField(help_text='Corporate email address for the student.', max_length=254, unique=True)),
                ('monitor', models.CharField(blank=True, default='', help_text="Text describing the student's monitor status.", max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text="The student's account status.", max_length=50)),
                ('user_data', models.OneToOneField(help_text='The associated user data record.', on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to='seletivo.userdata')),
            ],
            options={
                'verbose_name': 'Student Data',
                'verbose_name_plural': 'Student Data',
                'ordering': ['registration'],
                'indexes': [models.Index(fields=['registration'], name='student_dat_registr_740e04_idx'), models.Index(fields=['corp_email'], name='student_dat_corp_em_5493ba_idx')],
            },
        ),
    ]
