# Generated by Django 4.2.21 on 2025-06-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='registration',
            field=models.CharField(help_text='A unique alphanumeric registration code (up to 20 characters, e.g., PDDB0004, PDITA001).', max_length=20, unique=True),
        ),
    ]
