# Generated by Django 4.2.21 on 2025-07-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0002_alter_studentdata_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='status',
            field=models.CharField(blank=True, default='active', help_text="The student's account status.", max_length=50),
        ),
    ]
