# Generated by Django 4.2.21 on 2025-06-05 16:43

import candidate.models.candidate_document_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seletivo', '0002_academicmeritdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.FileField(blank=True, null=True, upload_to=candidate.models.candidate_document_model.id_doc_upload_path)),
                ('id_doc_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10)),
                ('id_doc_refuse_reason', models.TextField(blank=True, null=True)),
                ('address_doc', models.FileField(blank=True, null=True, upload_to=candidate.models.candidate_document_model.address_doc_upload_path)),
                ('address_doc_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10)),
                ('address_doc_refuse_reason', models.TextField(blank=True, null=True)),
                ('school_history_doc', models.FileField(blank=True, null=True, upload_to=candidate.models.candidate_document_model.school_history_doc_upload_path)),
                ('school_history_doc_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10)),
                ('school_history_doc_refuse_reason', models.TextField(blank=True, null=True)),
                ('contract_doc', models.FileField(blank=True, null=True, upload_to=candidate.models.candidate_document_model.contract_doc_upload_path)),
                ('contract_doc_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10)),
                ('contract_doc_refuse_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_documents', to='seletivo.userdata')),
            ],
        ),
    ]
